services:
  - type: web
    name: hockey-planner
    runtime: static
    buildCommand: npm run build
    staticPublishPath: ./build
    routes:
      - type: rewrite
        source: /*
        destination: /index.html